name: Actualizar versión SQL

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ "master" ]
jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Incrementar versión en README.md
        run: |
            VERSION=$(grep -m1 'Versión' README.md | awk '{print $3}')
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
            NEW_VERSION="$MAJOR.$((MINOR+1)).0"
            sed -i "s/| Versión    | .*/| Versión    | $NEW_VERSION                            |/" README.md
            echo "Nueva versión: $NEW_VERSION"

      - name: Commit y push
        run: |
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add README.md
            git commit -m "Actualización automática de versión en README a $NEW_VERSION"
            git push origin main

