name: Actualizar versión SQL

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ "master" ]
jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Incrementar versión en README.md
        run: |
            VERSION=$(grep -m1 'Versión' README.md | sed -E 's/.*\|[[:space:]]*([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
            NEW_VERSION="$MAJOR.$MINOR.$((PATCH+1))"
            sed -i "s/| Versión    | .*/| Versión    | $NEW_VERSION                            |/" README.md
            echo "Nueva versión: $NEW_VERSION"



